export const BOARD_NAME_SPACE = {
  namespace: '/board',
};

export const BOARD_SCRIBE_EVENT = {
  JOIN_BOARD: 'JOIN_BOARD',
  LEAVE_BOARD: 'LEAVE_BOARD',
};

export const BOARD_EMIT_EVENT = {
  LEFT_BOARD: 'LEFT_BOARD',
  JOINED_BOARD: 'JOINED_BOARD',
  CREATED_BOARD: 'CREATED_BOARD',
};
