version: '3.7'

services:
  main:
    container_name: nest-docker
    image: truongvn/trello-nestjs
    restart: always
    ports:
      - '4000:4000'
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - redis
      - database
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
        delay: 1s

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - '.:/var/lib/redis'

  database:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - '.:/var/lib/mongo:rw'

networks:
  app-network:
    name: trello-nest-network-attach
    attachable: true






